# Generated by Django 4.2.1 on 2025-01-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_contact_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='category',
            field=models.CharField(choices=[('Lead', 'Lead'), ('Opportunity', 'Opportunity'), ('Account', 'Account')], max_length=11, null=True),
        ),
    ]
