# Generated by Django 4.2.1 on 2025-01-28 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_contact_mobile_number_and_more'),
        ('contacts', '0006_contact_category'),
    ]

    operations = [
    ]
