# Generated by Django 4.2.1 on 2025-03-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_alter_contact_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='category',
            field=models.CharField(choices=[('Prospect', 'Prospect'), ('Lead', 'Lead'), ('Opportunity', 'Opportunity'), ('Account', 'Account'), ('Customer', 'Customer'), ('Customer/Lead', 'Customer/Lead')], max_length=50, null=True),
        ),
    ]
