# Generated by Django 4.2.1 on 2025-04-03 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_alter_profile_alternate_phone_alter_profile_phone'),
        ('leads', '0002_alter_lead_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadStatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('assigned', 'Assigned'), ('in process', 'In Process'), ('converted', 'Converted'), ('recycled', 'Recycled'), ('closed', 'Closed')], max_length=255, null=True, verbose_name='Status of Lead')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.profile')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='leads.lead')),
            ],
            options={
                'verbose_name': 'LeadStatusHistory',
                'verbose_name_plural': 'LeadStatusHistory',
                'db_table': 'lead_status_history',
                'ordering': ('-changed_at',),
            },
        ),
    ]
