# Generated by Django 4.2.1 on 2025-02-27 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_created_by'),
        ('opportunity', '0002_alter_opportunity_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='leads.lead'),
        ),
    ]
